### ISSUE TITLE
price change update not using the right currency when in dollar

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#147]
as a User, if I go try to send $10 to a username, I'm going to the send screen, and set $10. 
now if the price change between the time the price in dollar is being set and the payment is being sent, the dollar amount sent is different.

The reason is that when setting a price in dollar, the reference is not the dollar but the sats amount. 

let's say $10 for 10,000 sats. for a 1000 sats per $1. now if the price changes to 1100 sats per dollar, the amount of sats would still be 10000, but the calculated price in dollar would be 10000/1100 = $9.09

**Comment by jrbuhl93** [comment]
I see a couple possible ways to fix this:

1. Poll for price updates more frequently when on the send screen.
2. Get the new price before sending a payment and updating the sat amount before the payment request is made.
3. Add support for sending payments in dollars to the server and handle the logic server side.

I think 3 would be best because it minimizes latency, and to me it makes sense to have the logic for sending dollar payments server side.

**Comment by nicolasburtey** [comment]
> Poll for price updates more frequently when on the send screen.

this would not fix the issue. the issue is because our unit of account is in sats but it should be in dollar

this is a client side issue. we need to have the reference price in dollar, not in sats. 

current the price in dollar is converted in memory in sats and sats is the reference number. so if price of sats/usd change, then we updated the USD. instead we should keep USD constant and update the number of sats being sent.

**Comment by jrbuhl93** [comment]
Fixed in #172
