### ISSUE TITLE
palette refactoring

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#2202]
- fix e2e test

components:
- revisit `<TextInput />` and make them consistent / galoy input component doesn't really work

design:
- galoy secondary button need some outline
- galoy tertiary button too small

colors:
- button in dark mode is too bright
- colors needs more consistency / colors.ts need more shrinking.
- grey4 in white mode is a bit light

**Comment by UncleSamtoshi** [comment]
Follow up:
- GaloySecondaryButton: I think it makes sense to keep no outline, and in the cases where there are muliple buttons required (currently just the error screen) switch to either multiple primary buttons or create a separate component that is better suited for multiple options
- GaloyTertiaryButton: This button is currently used in two place (the error screen) and the "Contact Us" button. I agree that for the error screen the button is too small and we can switch to either the GaloyPrimaryButton as a work around. For the "Contact us" button, I think it makes sense to keep it small because it is supposed to be a footer/extra button that doesnt draw attention.
