### ISSUE TITLE
Move Styling to Tailwind-RN alongside RNE

### ISSUE THREAD

**Issue by sandipndev** [GaloyMoney/galoy-mobile#2571]
I have used https://github.com/vadimdemedes/tailwind-rn previously and didn't need to write so much stylesheet stuff, tailwind is heaviliy readable as well. Opinions? Comments?

**Comment by nicolasburtey** [comment]
I have never used tailwind, so I don't have a particular experience or strong input with that option, but we used to use https://www.npmjs.com/package/react-native-extended-stylesheet before. 

I remove the use of this library maybe 6 month-ish ago because it was not based on typescript, and so we would not know if we are using invalid type.

it seems this library is similarly unmaintained, so I'm not sure we should really go that path.

**Comment by nicolasburtey** [comment]
a look at the issues shows the issues popping regarding the fact the library is unmaintained on types and new features: https://github.com/vadimdemedes/tailwind-rn/issues
