### ISSUE TITLE
Unintentional deconnection

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#2871]
In the opening screen when Face ID or pin is requested, there is an option to disconnect the user

We should have a confirmation message when tapping disconnect to avoid a user unintentionally logging out from his account

**Comment by MaxwellDG** [comment]
@nicolasburtey  While investigating this, I found 3 other bugs I'd like to include in this issue:

1. If biometrics is enabled, pressing logout also retriggers the biometrics modal to be asked for simultaneously. 
2. Logging out immediately logs the user back into the app as a 'guest'. Is this intentional? I was expecting to be brought to the landing screen once I logged out.
3. Logging out clears all cached user settings. This means that logging out returns the biometrics and pin settings to default (disabled). And there's probably other settings that get removed too. At least for this issue, I propose not wiping the cache entirely clean on logout. Or at absolute least, I could include a message in the 'Confirmation message' that says "logging out will wipe all your settings".
