### ISSUE TITLE
Faster sending to Blink user from Send screen

### ISSUE THREAD

**Issue by designsats** [GaloyMoney/galoy-mobile#2979]
Just instantly to step2 of send flow (amount selection) when tapping username on step1 of Send flow. Remove the need to tap "Continue"

**Comment by MaxwellDG** [comment]
@designsats Updated in #2981 

You'll notice there's a half-second lag after pressing the button. It responds with a loader, but it's still not instantaneous. This is because of confirming the destination as valid. If you think this is still too slow, let me know and it can be improved. Would require some discussion with backend.
