### ISSUE TITLE
Users of BBW are sending by Mistake Transactions by username believing we share usernames with other wallets.

### ISSUE THREAD

**Issue by SalimArgueta** [GaloyMoney/galoy-mobile#424]
Users of BBW are sending by Mistake Transactions by username believing we share usernames with other wallets. they believe if they write his name or the word CHIVO in the username place, their money goes to his own chivo wallet. resulting to send another user.

I think maybe we can add a text below this place like “We don’t share usernames with other wallets” for the users to know. or something like this.

<img width="274" alt="Screen Shot 2022-03-30 at 5 32 44 PM" src="https://user-images.githubusercontent.com/86983536/160947533-f231a911-492e-41cc-8a6e-1dafb9f00788.png">

**Comment by daviroo** [comment]
I think that rather than have a warning persistently on the send bitcoin screen we should have a warning screen which shows for the user every time they pay to a username which they haven't paid to before.  The warning screen should contain a checklist of common mistakes/fraud which can occur while paying to username.  Below is an example of a warning screen I'm presented with when I pay someone new from my fiat banking app.
![image](https://user-images.githubusercontent.com/3502409/161007091-5046b13c-1b9f-4786-b4a7-a769b076ec4b.png)

I think this way is better as it only shows the warning when really necessary.

**Comment by daviroo** [comment]
> The problem is they will continúe making that (sometimes more than 4 times). And some time is for bigger amounts. But is your call. This problem will persist. And the amounts of the users will be lost.

But if the screen contained a warning that usernames are not shared with other wallets.  Are you suggesting that the warning screen would not be enough?

**Comment by SalimArgueta** [comment]
The warning screen could be every time they enter a username. Because sometime misspelling like Jackie for Jacky. Jorgev for Jorgeb. Sometimes they believe writing their name will send to chivo wallet or strike.

**Comment by SalimArgueta** [comment]
But what if they already do the misspelling before? or accepted once? maybe like a "Are you shure to send to *user*" if they alredy do. and "Are you shure to send to *user*, you never send payments before" for the new ones. I know maybe for us is easy to understand, but here is a hard time to deal with some wallet users. like the one of the first screenshot of $177. he claims to work on salvadorian presidential house and want this ammount back. even when I expleain sereveral times "chivo" is a BBW username not the wallet.
