### ISSUE TITLE
Don't block payment on failed fee probe

### ISSUE THREAD

**Issue by UncleSamtoshi** [GaloyMoney/galoy-mobile#554]
Current Behavior: A payment is blocked when the fee probe fails.

Desired Behavior: Don't block payment and have a more helpful error message.

**Comment by nicolasburtey** [comment]
If the fee is for onchain the payment will most likely fail anyway (onchain wallet depleted)

Where the behavior is different is with lightning when probe doesn't always works

**Comment by nicolasburtey** [comment]
And the message is indeed very misunderstood by the users

**Comment by nicolasburtey** [comment]
because "fee probe unsuccessful" (or whatever is the message we have now) is not something user really understand. ie: the concept of probing over the lightning is too technical in nature and showing max fees is a better behavior for instance. 

right now we're blocking the payment when fee is pending. but previous behavior (v1+) was to allow payment even if fee probe was pending, when we would return the result of the query we would either 1/ show the fees 2/ show the errors above. I'm talking about the error above.

**Comment by daviroo** [comment]
I was confused because I didn't understand why we would display an error but allow the user to continue, but I understand now.  The way I see it we have two options.

1.  Display something like "unknown" in the fees field in the event that the call fails.  We can also show a question mark icon next to it which will allow the user to tap on it to display more information about why the fees are unknown if they want to know more.
2. Display the max fee in the fees field in the event the call fails.  Again we could show a question mark icon next to it which could display a modal explaining that this is max fee but it might end up costing them less once payment is made.

**Comment by daviroo** [comment]
Also I see we have added the logic to return early from the fee probe on the backend which is great https://github.com/GaloyMoney/galoy/pull/1420

**Comment by nicolasburtey** [comment]
agree for option 2. 

we should also lower the amount of max fees. currently it's 2% AFAIR. This could be 0.5% instead.
