### ISSUE TITLE
Add new google analytics events to the app

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-mobile#597]
- What payment method is being used to send transaction (e.g. pay by username, scan QR code, etc...)

**Comment by nicolasburtey** [comment]
- log when there is a text request from a phone number
- log when there is a login event

- --> look at the funnel at text request to login. a large dropoff would mean that there is a lot of users who are unable to login
- --> look at the number of multiple request for phone number in a same sessions --> another metrics that would help us to understand the text issues

**Comment by milig02** [comment]
I've put my questions in order of priority (The first one being more important than the last one)

1. Find out the % payments that were initiated by [a,b,c,d,e,f,g] over the past 90 days
a. Scanning a QR code starting from the Send page
b. Typing manually a BBW contact
c. Pasting an invoice/bitcoin address from clipboard
d. Typing a Lightning address
e. Uploading an image
f. Clicking “Pay this merchant” from the map screen
g.Clicking “Send” from the individual contact page

2. Find out the % payments that were initiated starting with the Scan page vs the Send page over the past 90 days. 

3. Find out how often do the users use Send and Receive? Separate unintentional (bounce/no action) and intentional (take an action) over the past 90 days. (The purpose of this question is so I can compare its answer with the answer of #4, #5 and #6)

4. How often do users go to these pages from the navigation tab? Separate unintentional (bounce/no action) and intentional (take an action) over the past 90 days.
 a. Contacts
 b. Map 
 c. Earn

5. Find out how often do users go to view their transaction history? Separate unintentional (bounce/no action) and intentional (take an action) over the past 90 days.

6. Find out how often people go to the price graph (2-3 week, once a week, every 2 weeks, every month, etc). Separate unintentional (bounce/no action) and intentional (take an action) over the past 90 days.

7. What’s the % of users who set their username?

**Comment by daviroo** [comment]
> Find out how often do the users use Send and Receive? Separate unintentional (bounce/no action) and intentional (take an action) over the past 90 days. (The purpose of this question is so I can compare its answer with the answer of 4, 5 and 6)

Defining a bounce:
- If user enters a screen and then leaves within x seconds (maybe 3-5).  Might also be different for different screens (less for receive screen)
